"""LangChain tool for automated demand report generation."""

import json
from datetime import datetime

from langchain_core.tools import tool

from src.utils import get_config, get_logger

logger = get_logger(__name__)


@tool
def generate_demand_report(
    sku_id: str,
    forecast_json: str,
    anomaly_json: str,
) -> str:
    """
    Generate a formatted demand planning report combining forecast and anomaly data.

    Args:
        sku_id: The SKU this report covers.
        forecast_json: JSON string from the forecast_demand tool.
        anomaly_json: JSON string from the detect_anomalies tool.

    Returns:
        A formatted Markdown report string with demand insights and recommendations.
    """
    try:
        forecast = json.loads(forecast_json)
        anomalies = json.loads(anomaly_json)
    except json.JSONDecodeError as e:
        return f"Error parsing input data: {e}"

    # Check for errors in inputs
    if "error" in forecast:
        return f"Cannot generate report: forecast error for {sku_id}: {forecast['error']}"
    if "error" in anomalies:
        return f"Cannot generate report: anomaly detection error for {sku_id}: {anomalies['error']}"

    report_date = datetime.now().strftime("%Y-%m-%d")

    # Build report sections
    lines = [
        f"# Demand Planning Report: {sku_id}",
        f"**Generated:** {report_date}",
        "",
        "## Executive Summary",
        "",
        f"This report covers demand forecasting and anomaly analysis for **{sku_id}**.",
        "",
        "## Forecast Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Model Used | {forecast.get('model', 'N/A')} |",
        f"| Forecast Horizon | {forecast.get('horizon_days', 'N/A')} days |",
        f"| Average Daily Demand | {forecast.get('forecast_mean', 'N/A')} units |",
        f"| Total Projected Demand | {forecast.get('forecast_total', 'N/A')} units |",
        f"| Confidence Lower Bound | {forecast.get('confidence_lower', 'N/A')} |",
        f"| Confidence Upper Bound | {forecast.get('confidence_upper', 'N/A')} |",
        "",
    ]

    # Anomaly section
    anomaly_count = anomalies.get("anomaly_count", 0)
    summary = anomalies.get("summary", {})

    lines.extend(
        [
            "## Anomaly Detection",
            "",
            f"**Method:** {anomalies.get('method', 'N/A')}  ",
            f"**Data Points Analyzed:** {anomalies.get('data_points_analyzed', 'N/A')}  ",
            f"**Anomalies Found:** {anomaly_count}  ",
            f"**Spikes:** {summary.get('spike_count', 0)} | **Drops:** {summary.get('drop_count', 0)}",
            "",
        ]
    )

    if anomaly_count > 0:
        lines.append("| Date | Demand | Expected | Deviation | Type | Severity |")
        lines.append("|------|--------|----------|-----------|------|----------|")
        for a in anomalies.get("anomalies", [])[:10]:  # Top 10
            lines.append(
                f"| {a['date']} | {a['demand']} | {a['expected_mean']} | "
                f"{a['deviation_pct']}% | {a['type']} | {a['severity']} |"
            )
        lines.append("")

    # Recommendations
    lines.extend(
        [
            "## Recommendations",
            "",
        ]
    )

    forecast_total = forecast.get("forecast_total", 0)
    if forecast_total > 0:
        safety_stock = round(forecast_total * 0.15, 2)
        lines.append(
            f"1. **Reorder Quantity:** Plan for approximately {forecast_total} units "
            f"over the next {forecast.get('horizon_days', 30)} days."
        )
        lines.append(
            f"2. **Safety Stock:** Maintain a buffer of ~{safety_stock} units "
            f"(15% of projected demand) to handle variability."
        )

    if anomaly_count > 0:
        spike_count = summary.get("spike_count", 0)
        drop_count = summary.get("drop_count", 0)
        if spike_count > drop_count:
            lines.append(
                "3. **Anomaly Action:** Multiple demand spikes detected. "
                "Investigate potential causes (promotions, seasonality, supply disruptions)."
            )
        else:
            lines.append(
                "3. **Anomaly Action:** Demand drops detected. "
                "Review for data quality issues or market shifts."
            )
    else:
        lines.append("3. **Anomaly Status:** No significant anomalies detected. Demand pattern is stable.")

    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by Demand Planning System on {report_date}*")

    report = "\n".join(lines)
    logger.info(f"Generated report for {sku_id} ({len(lines)} lines)")

    return report
